### ISSUE TITLE
No Longer Getting Rich Notifications On iOS 13 Beta 5

### ISSUE THREAD

**Issue by tarbychark** [KhaosT/homebridge-camera-ffmpeg#332] opened 2019-07-31 16:23 UTC
My current home hubs are Apple TVs also running tvOS 13 beta 5. Motion notifications still come through, but I’m no longer getting image previews. Let me know if there is any logging you might need.

**Comment by Yardco** [comment] 2019-08-02 09:21
Me neither unfortunately...

**Comment by jankais3r** [comment] 2019-08-02 21:43
How does one setup these notifications? Is having a camera and motion sensor in the same HomeKit room enough or is the setup more involved?

**Comment by tarbychark** [comment] 2019-08-02 21:56
> How does one setup these notifications? Is having a camera and motion sensor in the same HomeKit room enough or is the setup more involved?

Yep, if you have a camera in a room with a motion sensor, it will include a still image in the motion notification (or at least it used to in iOS 12).

**Comment by senseotech** [comment] 2019-08-18 20:11
I'v actually not been getting rich notifications for the entire duration of iOS13/tvOS13 betas.  That said, I got a Circle 2 with active HomeKit support yesterday and its doing rich notifications.  I looked at how its set up in HomeKit and it looks like the Camera itself is publishing the motion sensor as an accessory; wonder if some change in iOS 13 is preventing rich notifications if the cam and sensor are just in the same room (aka they need to be grouped together ala the Circle 2 camera.)

**Comment by tarbychark** [comment] 2019-08-18 20:17
That sounds like it could definitely be a possibility. I've also been using homebridge-dafang, which uses the cameras themselves as motion sensors, but configured as a separate accessory. Wonder if the dev behind that plugin might be able to solve it by merging them as single accessories, rather than separate?

**Comment by senseotech** [comment] 2019-08-19 00:38
> That sounds like it could definitely be a possibility. I've also been using homebridge-dafang, which uses the cameras themselves as motion sensors, but configured as a separate accessory. Wonder if the dev behind that plugin might be able to solve it by merging them as single accessories, rather than separate?

To add credence to my suspicion, I just enabled motion alerts on a machine still running Mojave and confirmed that its getting rich notifications with a snapshot when nothing running Catalina/iOS 13 does, but everybody is happy with the Circle 2 device thats got the motion sensor nested inside it.

**Comment by tarbychark** [comment] 2019-08-19 00:47
Yep, same here. Mac mini on 10.14.6 still receives them just fine.

**Comment by iuliusmaximilian** [comment] 2019-08-29 19:59
+1

**Comment by iuliusmaximilian** [comment] 2019-08-30 06:27
@KhaosT Can you please investigate in this really bad one

**Comment by iuliusmaximilian** [comment] 2019-08-30 08:11
Can confirm that Rich Notifications are still received on macOS 10.14.6 with tvOS 13.1 public beta and not received on iOS and iPadOS 13.1 public betas.

**Comment by dkrizic** [comment] 2019-09-20 21:24
It looks like that the Camera and the Motion Sensor must be in the same device. I have a real Omna which offers exactly this. Now with iOS 13 the Omna continues to send rich notifications. All other combinations where I have a Camera and Motion Sensor (as separate devices) does not work. I get the motion notification, but without a picture. Looks like we need a change in Homebridge that two devices can be combined into one.

**Comment by ashtonaut** [comment] 2019-09-21 07:10
Same issue here after updating to iOS 13 on my phone. Still running tvOS 12 on my Apple TV. Motion sensor notifications generated via  homebridge-filesensor aren’t rich notifications with a snapshot.

I understand the logic of why this is likely happening - super keen for a fix or workaround that allows us to combine the sensor into the camera within homebridge somehow!

**Comment by NorthernMan54** [comment] 2019-09-22 11:48
My first thought is that this feature gap is a result of tvOS and iPadOS not being updated yet, so am thinking to wait until they are updated.  Also I saw a comment saying 13.1 is coming in a week or 2, so maybe it is fixed there.

I’m going to just wait for a few weeks and see where things land, before crafting a workaround for this.

**Comment by tarbychark** [comment] 2019-09-22 15:40
Still same issue running latest 13.1 betas on iPhone and iPad as well as 13 GM on both of my Apple TV’s. Looking like a workaround will indeed need to be crafted.

**Comment by Maxwell70** [comment] 2019-09-23 07:30
@KhaosT I confirm, after updating on ios 13 screenshots are not sent! I beg you to solve this problem!

**Comment by KhaosT** [comment] 2019-09-23 15:11
It looks like in iOS 13, HomeKit will no longer try to use separate motion sensors in a room to trigger camera notification. In order for notification to appear, the motion sensor service has to be in the same accessory as the camera itself.

Can you guys share what kind of motion sensors are you guys using right now?

**Comment by tarbychark** [comment] 2019-09-23 15:15
> It looks like in iOS 13, HomeKit will no longer try to use separate motion sensors in a room to trigger camera notification. In order for notification to appear, the motion sensor service has to be in the same accessory as the camera itself.
> 
> Can you guys share what kind of motion sensors are you guys using right now?

Right now, I'm using homebridge-dafang for Wyze cameras, which uses the camera's software motion detection to create a motion sensor accessory.

I also have a couple Phillips motion sensors in rooms with cameras.

**Comment by iuliusmaximilian** [comment] 2019-09-23 15:53
I am on iOS 13.1 and iPadOS 13.1 and tvOS 13 - no rich notifications for this circumstance anymore :-(

**Comment by ashtonaut** [comment] 2019-09-24 05:07
@KhaosT

my cameras are running through homebridge-camera-ffmpeg.

My motion sensors are all using homebridge-filesensor.

I have one motion sensor and one camera in each room.

Thanks for looking into this!

**Comment by phralh** [comment] 2019-09-24 05:28
Hue and IKEA trådfri sensors through homebride-hue. 
Support for triggering motion with mqtt would be nice.

**Comment by Maxwell70** [comment] 2019-09-24 06:59
> Похоже, что в iOS 13 HomeKit больше не будет пытаться использовать отдельные датчики движения в комнате для запуска уведомления камеры. Чтобы появилось уведомление, служба датчика движения должна быть в том же аксессуаре, что и сама камера.
> 
> Ребята, не могли бы вы рассказать, какие датчики движения вы сейчас используете?

I use motion sensors Aqara through the plugin homebridge-mi-aqara. Probably need once in our plugin to embed the motion sensor with the camera.

**Comment by Maxwell70** [comment] 2019-09-24 07:00
> It looks like in iOS 13, HomeKit will no longer try to use separate motion sensors in a room to trigger camera notification. In order for notification to appear, the motion sensor service has to be in the same accessory as the camera itself.
> 
> Can you guys share what kind of motion sensors are you guys using right now?

I use motion sensors Aqara through the plugin homebridge-mi-aqara. Probably need once in our plugin to embed the motion sensor with the camera.

**Comment by NorthernMan54** [comment] 2019-09-24 10:10
I was thinking of 2 potential approaches for merging a motion sensor from another plugin into a camera accessory.

First perform some hackery on hap-nodejs and have it merge a motion sensor service object into a camera accessory.  Not sure if this was feasible as I haven’t looked into it yet, also would require the camera accessory and motion sensor plugin to be in the same homebridge instance.

Second approach, have the existing camera-ffmpeg plugin perform a proxy function for existing motion sensor accessories and merge it into the camera.  And for the proxy code, could reuse some of the code from my homebridge-Alexa plugin which already does device discovery and control.

Any other thoughts on approaches to resolve?  Personally I thought this would have caused more noise outside of this community, which I haven’t noticed yet.

PS all this would be limited to motion sensors and cameras exposed thru homebridge / hap-nodejs, native HomeKit devices would not work

**Comment by NorthernMan54** [comment] 2019-09-24 11:29
Approach 3,  in the existing camera-ffmpeg plugin add a dummy motion sensor and switch, and have the switch trigger the motion sensor on/off.  Then use an automation to turn on/off the switch when the real motion sensor sees motion.

This seems the easiest.  Any thoughts from everyone else?

**Comment by tarbychark** [comment] 2019-09-24 17:47
Looking forward to whatever option you boys decide to move forward with. Wish I was skilled enough to assist.

**Comment by BadgerBadgerAndFox** [comment] 2019-09-25 00:30
Confirmed as not working also on iOS 13.1 Beta 4
I'm running 1 camera in "homebridge-camera-ffmpeg" with the RTSP feed from Synology Surveillance Station.
Motion sensor is provided from "homebridge-sss-platform".

I'm also feeding a further 5 cameras from Unifi Protect using "homebridge-unifi-protect2".
Motion sensors for the Unifi cameras are provided by "homebridge-unifi-protect-motion-sensors".

Homebridge is running in Docker container from oznu/homebridge on the Synology DiskStation.

Each camera has the same display name as the associated motion sensor and is located in the same room in HomeKit, and as with others the rich notifications worked prior to iOS 13.x

@KhaosT Let me know if there is anything else i can provide to assist.

**Comment by NorthernMan54** [comment] 2019-09-25 02:52
Alpha code for my approach #3 is here

https://github.com/NorthernMan54/homebridge-camera-ffmpeg/commit/a29948e21ffdecbb8ab99d46a0c6f5123fd6fc7c#diff-168726dbe96b3ce427e7fedce31bb0bc

The change only applies to index.js

Please note my repo has some other things I'm working on to improve WyzeCam RTSP feeds, and google photo uploading so please don't install my repo as it will not work for you.

**Comment by NorthernMan54** [comment] 2019-09-25 03:28
And a quick test was a success, but need to work thru some variable scope issues.  ( I have 2 cameras, and I walked in front of the first and the second triggered)

**Comment by iuliusmaximilian** [comment] 2019-09-25 05:11
Great, thanks for sharing !! Having 9 cameras and 11 PIR so better I wait right ?

**Comment by rgazaryants** [comment] 2019-09-25 05:20
FWIW, I use camera-ffmpgeg & homebridge-web-motion.
I have a separate process monitoring my Hikvision cameras for events & makes the http calls to web-motion listeners.

**Comment by ashtonaut** [comment] 2019-09-25 10:31
@NorthernMan54 thanks for giving this Somme attention! I’m also surprised there hadn’t been more widespread grumbling.

I don’t know if I’m competent enough to test your alpha solution, but I’m happy to test and report back if given some instructions on what and how to test. I have 4 cameras with 4 homebridge-filesensor motion detectors, simple setup with a single camera and single motion detector in each ‘room’.

**Comment by NorthernMan54** [comment] 2019-09-25 13:20
A couple of screenshots from my poc code, looks good so far



![B4CC23B8-BE6B-417B-8BAA-A952A894E4E2](https://user-images.githubusercontent.com/19808920/65602543-100c0600-df72-11e9-929a-e32936c33af6.png)
![EBEF8D75-34D5-47B2-B02C-77D33D450EF7](https://user-images.githubusercontent.com/19808920/65602545-100c0600-df72-11e9-812b-2d0ce89d4233.png)

**Comment by tarbychark** [comment] 2019-09-25 15:16
Great progress so far!

**Comment by iuliusmaximilian** [comment] 2019-09-25 15:48
Just tested by replacing the index.js (only). The result is all cameras now have a switch and a motion sensor and enabling the switch manually sends rich notifications. As described above, atm. from the wrong camera.

**Comment by NorthernMan54** [comment] 2019-09-26 00:31
Beta code for this is Pull Request #355 

@KhaosT Take a look and see what you think

**Comment by NorthernMan54** [comment] 2019-09-26 01:05
Fixed multiple camera’s as well


![5CEB8E8E-E961-4A8A-AEE8-68E7F3E992FA](https://user-images.githubusercontent.com/19808920/65650276-2c428e00-dfd8-11e9-946c-e2771a0b703d.png)

**Comment by fennec622** [comment] 2019-09-26 01:11
Thanks i try and it's ok

Now how can i do for active motion detect, try to add mqtt

**Comment by rgazaryants** [comment] 2019-09-26 01:17
> Last step would be updating the README with the new functionality

Perhaps a config parameter for motion reset? Looks like it's fixed to 5sec.

**Comment by Maxwell70** [comment] 2019-09-26 02:00
@KhaosT Strongly waiting for the plugin update! Thanks a lot!

**Comment by ashtonaut** [comment] 2019-09-26 02:35
@NorthernMan54 for those of us keen to try this in advance of an official merge, can you please help out with what I need to do? Is it as simple as replacing a couple of files within the homebridge install or config? Cheers

**Comment by NorthernMan54** [comment] 2019-09-26 02:49
@ashtonaut Just replace the index.js from my patch into your environment and restart homebridge, then add the required automation rules in the home app

@rgazaryants I spent a fair bit of time thinking about this, and originally required a second automation rule to turn it off.  But after playing with it for a bit realized that you only needed the "On" or "Motion" trigger and how long it stayed on was meaning less for the workaround.  So I hardcoded 5 seconds, so that it stayed ON long enough to notice, but also reset fast enough that you motion sensor could trigger it again ( if needed ).

@fennec622 Sorry can't help with the MQTT bit

**Comment by fennec622** [comment] 2019-09-26 03:14
@NorthernMan54 thanks, you how do you active motion detect ?

**Comment by NorthernMan54** [comment] 2019-09-26 03:18
Just create an automation rule for when your real motion detects something to turn on the switch with the same name as your camera

**Comment by tarbychark** [comment] 2019-09-26 03:20
> @NorthernMan54 thanks, you how do you active motion detect ?

![IMG_0043](https://user-images.githubusercontent.com/8187837/65655676-fce94c80-dfea-11e9-9992-95b1a3d17afd.jpeg)

![IMG_0044](https://user-images.githubusercontent.com/8187837/65655685-05418780-dfeb-11e9-8dc5-44d074546a0e.jpeg)

**Comment by rgazaryants** [comment] 2019-09-26 07:35
Thanks to @NorthernMan54 for laying the groundwork.

I wanted to go a little bit into a different direction, and hacked in homebridge-web-motion without adding its own motion sensors. I know enough JS to cause damage, so I probably did some hacky things.

https://github.com/rgazaryants/homebridge-camera-ffmpeg/commit/d3b188c28d5744ba66544b7ea151d55b4f650d59

It works the same as with the web-motion plugin. You basically trigger motion on/off with sending a GET request to like:
`http://172.16.0.9:2000/sidew/motionDetected/1` & `http://172.16.0.9:2000/sidew/motionDetected/0` for off

`http://172.16.0.9:2000/front_door/motionDetected/1` & `http://172.16.0.9:2000/front_door/motionDetected/0`

In the case of front_door, My camera is named "Front Door" in ffmpeg config. For the sake of simple URLs, the camera name is converted to lower case, and spaces replaced with underscores. Any special characters in the name will likely break it.

Some extra config for the json:
```
"platform": "Camera-ffmpeg",
  "autoResetMotion": true,
  "autoResetDelay": 15,
  "motionPort": 2000,
  "cameras": [
    {
...
...
```

**Comment by roe1974** [comment] 2019-09-26 08:42
is it not possible to just group the motion sensor and the camera to one group ?
Perhaps to ad a parameter in the config.json for the "real" motion sensor ?
Sorry i am not fit in JS, just an idea ;-)

Richard

**Comment by BadgerBadgerAndFox** [comment] 2019-09-26 11:24
@NorthernMan54 You sir are a legend! Dropped in the current code from your pull request and it works great!. I alos injected your changes into the index.js for hjdhjd/homebridge-unifi-protect2 and it works in there as well! Now all my cameras get rich notifications again.
Would you be able to submit your pull request to homebridge-unifi-protect2 as well?

**Comment by NorthernMan54** [comment] 2019-09-26 11:48
@BadgerBadgerAndFox There is no magic about pull requests, you can submit your changes to the index.js for homebridge-unifi-protect2 directly.  ( on the github website, just edit the file and it will create a pull request for you )

@roe1974 not feasible as each motion sensor has a unique work around

**Comment by ScharV** [comment] 2019-09-26 14:46
@NorthernMan54 I saw that you forked homebridge-dafang for a while. Would it be possible to get a solution for the rich motion problem on this plugin to?

**Comment by NorthernMan54** [comment] 2019-09-26 16:41
@ScharV I abandoned that with my WyzeCam’s due to stability and image quality issues ( Night Vision ).  And am currently working on an approach based on the Wyze RTSP firmware, node-red and camera-ffmpeg ( the version in my fork ). Still a work in progress, but so far it has been positive.

**Comment by ScharV** [comment] 2019-09-26 16:50
@NorthernMan54 that sounds really good. Will it have the same functions as the dafang plugin?

**Comment by NorthernMan54** [comment] 2019-09-26 16:54
@ScharV no, as I’m basing it on camera ffmpeg and the Wyze firmware.  My focus is on mimicing the Ring Camera with snapshots and videos stored to google photo’s.  I’m currently storing a high quality picture and 1 minute of video for each motion event.

**Comment by ScharV** [comment] 2019-09-26 18:00
@NorthernMan54 would it be possible to help me to get it work on dafang plugin?

**Comment by phralh** [comment] 2019-09-26 19:45
Great work! 

I really would like support for triggering motion with a mqtt message to avoid adding extra dummy switches. I wish I was skilled enough to make it happen.

@ScharV If we could get mqtt support you could expose the dafang video stream through homebridge-camera-ffmpeg. Dafang hacks sends mqtt message for motion which the camera plugin could listen for and trigger a rich notification.

**Comment by ScharV** [comment] 2019-09-26 19:52
@phralh that sounds very good but i don‘t want to miss camera movement Accessoires

**Comment by phralh** [comment] 2019-09-26 20:21
@ScharV You don't have to move more than the rtsp stream, and you can delete accessories you don't need in config.json. Keep the controls!

I currently have one dafang exposed with dafang plugin for control, and one dafang exposed with mqttthings plugin for control (I find it easier and more powerful to setup control via node-red). Both videostreams is exposed to homebridge using homebridge-ffmpeg-camera.

**Comment by ScharV** [comment] 2019-09-26 21:08
Thats an interesting way🤔

**Comment by fennec622** [comment] 2019-09-27 02:24
Thanks for all 
I adapt to mqtt and all is ok 
when i have time i publish on git

**Comment by tarbychark** [comment] 2019-09-27 02:46
> @ScharV You don't have to move more than the rtsp stream, and you can delete accessories you don't need in config.json. Keep the controls!
> 
> I currently have one dafang exposed with dafang plugin for control, and one dafang exposed with mqttthings plugin for control (I find it easier and more powerful to setup control via node-red). Both videostreams is exposed to homebridge using homebridge-ffmpeg-camera.

I have pretty much the same setup. MQTT functions from homebridge-dafang combined with the stream in homebridge-camera-ffmpeg. 

Everything works like a charm now with the changes from @NorthernMan54!

Thanks for all of the hard work!

**Comment by pax0707** [comment] 2019-09-27 06:06
Works like a charm!

**Comment by nerosan** [comment] 2019-09-27 08:41
@NorthernMan54 Thank you for fixing this Problem. 

I replace the index.js with yours after that i got notification option on each of my cameras. i generate a dummy switch with homebridge-fhem plugin an named the cam, switch an room all the same. i generate a rule as described, but i don´t get rich notification ? do i have to generate the switch dummy a special way ? thank you!

**Comment by NorthernMan54** [comment] 2019-09-27 10:42
@tarbychark as this was merged last night, can you close this

Just a comment for everyone else, one side effect of the change is that each device now sends an individual snapshot request when motion is detected, and this causes a mini DDOS attack on my camera.  During my last round of testing I counted 4 snapshot requests at once to my camera.  Where previously it was a single request.

Just a heads up, as you may now encounter resource constraints on your homebridge instance or camera, if you have a lot of iOS devices.

**Comment by iuliusmaximilian** [comment] 2019-09-27 10:53
Quick question, has anyone this working with a conditional automation e.g. with an if then clause on HomeKit Shortcut instead of toggle the switch on. I wanted to use a virtual (HomeMatic) Variable als switch to toggle Notification on/off in general and include this virtual switch into an if then clause within the automation to toggle the camera motion switch on - but this does not work whyever.

**Closed** 2019-09-27 13:28 UTC

**Comment by black01gt** [comment] 2019-09-28 18:25
I updated and added motion true to my config but don’t get the switch or motion sensor.

**Comment by pax0707** [comment] 2019-09-28 20:06
Go to camera, settings.
Should see 2 accessories there.

**Comment by black01gt** [comment] 2019-09-28 20:08
Figured it out for some reason my homebridge plug-ins are being installed in a different location then they did when I installed.

**Comment by joselito11** [comment] 2019-10-03 04:22
Apple released ios 13.2 with homekit grouping, anyone tried if that also fix notifications?

**Comment by BadgerBadgerAndFox** [comment] 2019-10-03 04:40
@joselito11 wont help, that simply flips between post and pre ios 13 behavior for combined devices.
Under 13 combined devices place the accessories inside the parent object. Prior to 13 they appeared alongside them (in the same Homekit "room".
The code fix as implemented works great.

**Comment by joselito11** [comment] 2019-10-03 04:42
Just asking if maybe apple have fixed😀 I have implemented the code, and works fine.
